# Generated by Django 5.1 on 2024-10-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_upload_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
