# Generated by Django 5.1 on 2024-10-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_work_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='file',
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
