# Generated by Django 5.1 on 2024-10-26 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_work_file_alter_work_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='image',
            new_name='file',
        ),
    ]
